"""added index

Revision ID: 45fcd972e7b3
Revises: 3466667afe0c
Create Date: 2020-08-30 23:43:28.855218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fcd972e7b3'
down_revision = '3466667afe0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_id'), table_name='status')
    # ### end Alembic commands ###
