"""added index on domain

Revision ID: c27d2beba0c6
Revises: 45fcd972e7b3
Create Date: 2020-08-31 00:01:10.280534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27d2beba0c6'
down_revision = '45fcd972e7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_status_domain_name'), 'status', ['domain_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_domain_name'), table_name='status')
    # ### end Alembic commands ###
