"""added index on time

Revision ID: f1d4c170b824
Revises: c27d2beba0c6
Create Date: 2020-08-31 00:25:39.892359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d4c170b824'
down_revision = 'c27d2beba0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_status_last_update'), 'status', ['last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_last_update'), table_name='status')
    # ### end Alembic commands ###
